### ISSUE TITLE
Diamond Dust unobtainable

### ISSUE THREAD

**Issue by angelnc1989** [NerdHubMC/Refined-Machinery#7]
Putting a Diamond in the Pulverizer doesn't do anything for me and pulverizing Diamond Ore gives Diamonds.

**Comment by alothmanmoe** [comment]
Fixed in https://github.com/NerdHubMC/Refined-Machinery/commit/89e1a665a06fc18494579a84c1ccfa2337ccf6ef

**Comment by poboy975** [comment]
Has this been updated to the downloadable jar on curseforge? I'm still experiencing the same bug

**Comment by alothmanmoe** [comment]
No not yet sadly, been too busy past 2 days to be able to do much work on this mod, just finishing off something today so that i'll have the rest of the week to be able to work on RM
