### ISSUE TITLE
pulverized ores unobtainable

### ISSUE THREAD

**Issue by Dragonracer1973** [NerdHubMC/Refined-Machinery#8]
Hi like that you're taking the jump with tech mod for 1.14 it looks promising. My bug atm is while trying to obtain the crushed varients of the ores from the pulverizer, the dust disappears, and the stack of ore resets. While testing this, it appears that you will get two dust  ( and extra outputs included) however a right click makes them disappear and reset

**Comment by alothmanmoe** [comment]
Hey, which version of the mod are you using? I fixed all these issues in version 1.0.1 and am testing at the moment and it all seems to work fine

**Comment by Dragonracer1973** [comment]
never mind, the bug isn't they are unobtainable, its that it still shows up in the GUI output at nighttime, complete with the processing action, and output slots
